name: Build and Test Java Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Maven in Docker
      uses: docker://maven:3.8.4-openjdk-17
      with:
        args: mvn -f myapp/pom.xml clean install

    - name: Run tests
      uses: docker://maven:3.8.4-openjdk-17
      with:
        args: mvn -f myapp/pom.xml test
